# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r_packages:
  - covr
  - CholWishart
sudo: false
warnings_are_errors: true
cache: packages
os:
- linux
- osx
matrix:
  include:
  - r: devel
  - r: release
    after_success: Rscript -e 'covr::codecov()'
  - r: oldrel
  - r: 3.3
notifications:
  email:
    - gzthompson@gmail.com
after_success:
  - Rscript -e 'covr::codecov()'
