# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r_packages:
  - covr
  - CholWishart
  - pkgdown
sudo: false
warnings_are_errors: true
cache: packages
before_deploy: Rscript -e 'remotes::install_cran("pkgdown")'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true
  on: condition: name = "release"
os:
- linux
matrix:
  include:
  - r: devel
  - r: release
    name: "release"
    after_success: Rscript -e 'covr::codecov()'
  - r: oldrel
notifications:
  email:
    - gzthompson@gmail.com

